### ISSUE TITLE
cache-control header format

### ISSUE THREAD

**Issue by goofballLogic** [ForbesLindesay/http-basic#13]
It appears that in order to be cached, the cache-control header must match the following pattern: `/^public\, *max\-age\=(\d+)$/` (https://github.com/ForbesLindesay/http-basic/blob/master/lib/cache-utils.js#L14). However,

1. This appears to require that the cache-response-directive precede the cache-request-directive, and I don't see any such restriction in the spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9 . Furthermore, there are numerous examples around in various places of the directives being specified in the other order e.g. https://betterexplained.com/articles/how-to-optimize-your-site-with-http-caching/ . Is this a non-spoken convention which is widely adopted?
2. This string doesn't allow one to omit "public" (which many responders do)

**Comment by ForbesLindesay** [comment]
I only supported the one format because that's all I needed at the time, and most websites seem to provide headers of this form.  I'd be very happy to accept a pull request to fix this though.  Perhaps we could use something like https://github.com/roryf/parse-cache-control

I think we should be careful not to cache anything that's "private" by default.  I think a good default may be to require "public", but let the user opt in to caching more things.  You're definitely right that we should allow the header to be specified in any order.

**Comment by goofballLogic** [comment]
The spec specifically says: 

> The max-age directive on a response implies that the response is cacheable (i.e., "public") unless some other, more restrictive cache directive is also present.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.3

Shouldn't the default behaviour be the one in the specification?

**Comment by goofballLogic** [comment]
Happy to contribute a pull request once you OK the approach. I need a working lib to do proper caching rather urgently.

**Comment by ForbesLindesay** [comment]
Ok, I'm happy to go with the spec.  We just need to be confident that we don't cache if the header is invalid, marked as private or has a directive we don't recognise.
