### ISSUE TITLE
Timeout is not cleared when request finishes

### ISSUE THREAD

**Issue by johan13** [ForbesLindesay/http-basic#26]
When using the `timeout` option, then a timer is started with `setTimeout` but the timer is never cleared with `clearTimeout`. The timer will keep the node process from exiting until the timer expires.

This program will always take 60 seconds to exit:
```javascript
var request = require("http-basic");
request("GET", "https://github.com/", { timeout: 60000 }, (err, res) => {
    if (err) {
        console.log("Error:", err);
    } else {
        res.body.resume();
        console.log("OK");
    }
});
```

**Comment by johan13** [comment]
I was going to make a PR, but it turns out the project doesn't build and I notice that the last commit is 7 months ago. Is this project still being maintained?

(The build errors don't look too serious, by the way. Some compatibility problem with Typescript 2.6 and and other one with the typings for Node.js 8.)

**Comment by ForbesLindesay** [comment]
The project is still maintained, and you're likely to both waste a lot of time, and offend a lot of maintainers if you go around asking in issue trackers if projects are maintained.  The last commit is 7 months ago because this project is largely finished, apart from the occasional bug fix.

In any case, thank you for reporting this bug, I suspect there are a few people who have been suffering from this problem so I'll get it fixed in the next release.
